# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy firebase

on: 
  pull_request:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - run: npm ci
    - run: npm test -- --coverage --watchAll=false
      env:
        CI: true
  deploy:
    name: deploy
    needs: test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Use Node.js '${{ steps.nvm.outputs.NVMRC }}'
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - run: npm ci
    - run: npm run build
    - run: npm run deploy
  release:
    name: Create Release
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: GET Now
      run: echo ::set-output name=NOW::$(date '+%Y%m%d%S')
      id: now
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.now.outputs.NOW }}
        release_name: Release ${{ steps.now.outputs.NOW }}
        draft: false
        prerelease: false